---
abstract: 'Wrap file with headers/footers in Plack'
author:
  - 'Fayland Lam <fayland@gmail.com>'
build_requires: {}
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300003, CPAN::Meta::Converter version 2.102400'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Plack-Middleware-FileWrap
requires:
  Plack: 0
resources:
  repository: git://github.com/fayland/Plack-Middleware-FileWrap.git
version: 0.01
